name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host 9roommoa-ec2
            HostName $EC2_IP
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync Workspace to EC2 (Optimized)
        run: |
          ssh 9roommoa-ec2 'mkdir -p /opt/app'
          ssh 9roommoa-ec2 'sudo chown ubuntu:ubuntu /opt/app'
          rsync -avz --delete --exclude='.git' --exclude='node_modules' ./ 9roommoa-ec2:/opt/app/

      - name: Install dependencies if needed
        run: |
          ssh 9roommoa-ec2 'cd /opt/app && if [ -f package-lock.json ]; then npm ci; else npm install --legacy-peer-deps; fi'

      - name: Ensure PM2 is Installed
        run: |
          ssh 9roommoa-ec2 'if ! command -v pm2 &> /dev/null; then sudo npm install -g pm2; fi'

      - name: Restart Application with PM2 (if running)
        run: |
          ssh 9roommoa-ec2 'cd /opt/app && if pm2 list | grep -q "9roommoa"; then pm2 reload 9roommoa; else pm2 start app.js --name "9roommoa"; fi'

      - name: Save PM2 Process List
        run: |
          ssh 9roommoa-ec2 'pm2 save'

      - name: Check PM2 Process List
        run: |
          ssh 9roommoa-ec2 'pm2 list'
