name: Deploy to EC2 using PM2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa  # GitHub Secrets에서 비공개 키를 파일로 저장
          chmod 600 ~/.ssh/id_rsa  # 파일 권한 설정

          # SSH 설정 파일에 호스트 정보 추가
          cat >> ~/.ssh/config << 'EOF'
          Host ec2
            HostName ${{ secrets.EC2_IP }}
            User ec2-user
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF

      - name: Deploy to EC2
        run: |
          ssh ec2 'cd /home/ec2-user/capstone/aether_back && git pull origin main && npm install && pm2 restart 9roommoa'
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
