name: Deploy to EC2 using PM2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /Users/ec2-user/vscodeProject/capstone/9roomMoa
            git pull origin main
            npm install
            pm2 restart 9roommoa  # PM2로 애플리케이션 재시작
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
